# Generated by Django 5.2.17 on 2026-09-20 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('termos_uso', 'Termos de uso e política de privacidade'), ('telefone', 'Uso do telefone para contato')], max_length=30)),
                ('versao_termo', models.CharField(max_length=20)),
                ('concedido', models.BooleanField(default=True)),
                ('data_concessao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_revogacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de consentimento',
                'verbose_name_plural': 'registros de consentimento',
                'ordering': ['-data_concessao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_anonimo', models.CharField(blank=True, default='', max_length=64)),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso (consulta) aos dados'), ('exportacao', 'Exportação dos dados'), ('revogacao', 'Revogação de consentimento'), ('exclusao', 'Exclusão dos dados')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação do titular',
                'verbose_name_plural': 'solicitações do titular',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
