"""
Django settings for nivela project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    'usuarios',
    'turmas',
    'gamificacao',
    'chat',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nivela.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nivela.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
     'default': { 
         'ENGINE': 'django.db.backends.postgresql', 
         'NAME': 'nivela_db', 'USER': 'postgres', 
         'PASSWORD': config('DB_PASSWORD'), 'HOST': 'localhost', 
         'PORT': '5433', 
    } 
}

# Itens 1.1, 1.3 e 1.4 do requisito de autenticacao:
# O Django gera automaticamente um salt criptografico unico por
# usuario e armazena o hash + salt juntos no campo 'password' da
# tabela auth_user, no formato: algoritmo$iteracoes$salt$hash.
# Verificado manualmente via pgAdmin na tabela auth_user.

# Parametros de custo do hash de senha (PBKDF2-SHA256)
# Utilizamos o valor padrao do Django 5.2: 1.000.000 de iteracoes,
# que segue as diretrizes atualizadas da OWASP para resistencia a
# ataques de forca bruta em 2025+, equilibrando seguranca contra
# tempo de resposta aceitavel no login.
AUTH_PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# Configuracao de sessao (item 1.9 e 1.10)
# Sessao expira apos 30 minutos de inatividade
SESSION_COOKIE_AGE = 1800  # 30 minutos em segundos
SESSION_SAVE_EVERY_REQUEST = True  # renova o tempo a cada acao do usuario
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # expira ao fechar o navegador

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Protecao contra forca bruta (item 1.11)
AXES_FAILURE_LIMIT = 5  # bloqueia apos 5 tentativas erradas
AXES_COOLOFF_TIME = 1  # bloqueio dura 1 hora
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # bloqueia por usuario e IP

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',

]

# Configuracao do 2FA (itens 1.5 e 1.6)
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = 'two_factor:profile'