"""
Django settings for nivela project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Le a variavel DATABASE_URL fornecida automaticamente pelo Render em
# producao, ou usa a configuracao local (PostgreSQL na maquina do
# desenvolvedor) quando essa variavel nao existir
import dj_database_url
from urllib.parse import quote


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Le do .env (local) ou das variaveis de ambiente do Render (producao).
# Localmente fica True (mostra detalhes de erro); em producao deve ser
# False (esconde detalhes tecnicos do usuario final, exigido pelo
# Requisito 3 de comunicacao segura)
DEBUG = config('DEBUG', default=False, cast=bool)

# Lista de dominios autorizados a servir esta aplicacao, separados por
# virgula no .env/variavel de ambiente. Protege contra ataques de
# "Host header injection". Em producao, deve incluir o dominio do
# Render (ex.: nivela.onrender.com)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    'usuarios',
    'turmas',
    'gamificacao',
    'chat',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve os arquivos estaticos (CSS, imagens) diretamente pelo
    # Django em producao, sem precisar de um servidor separado
    # (necessario porque o Render nao roda um servidor de arquivos
    # estaticos dedicado como Nginx)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'usuarios.middleware.Force2FASetupMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nivela.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nivela.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Em producao (Render), dj_database_url le automaticamente a variavel
# de ambiente DATABASE_URL que o proprio Render fornece ao criar o
# banco PostgreSQL gerenciado. Localmente, essa variavel nao existe,
# entao cai no valor "default" abaixo, que monta a URL de conexao
# usando a senha do .env e o banco PostgreSQL da maquina do
# desenvolvedor (porta 5433).
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgresql://postgres:{quote(config('DB_PASSWORD'), safe='')}@localhost:5433/nivela_db",
        conn_max_age=600,
    )
}

# Itens 1.1, 1.3 e 1.4 do requisito de autenticacao:
# O Django gera automaticamente um salt criptografico unico por
# usuario e armazena o hash + salt juntos no campo 'password' da
# tabela auth_user, no formato: algoritmo$iteracoes$salt$hash.
# Verificado manualmente via pgAdmin na tabela auth_user.

# Parametros de custo do hash de senha (PBKDF2-SHA256)
# Utilizamos o valor padrao do Django 5.2: 1.000.000 de iteracoes,
# que segue as diretrizes atualizadas da OWASP para resistencia a
# ataques de forca bruta em 2025+, equilibrando seguranca contra
# tempo de resposta aceitavel no login.
AUTH_PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# Define o modelo de usuario customizado como o modelo de autenticacao
# padrao do projeto (necessario por causa do login por e-mail, RF02)
AUTH_USER_MODEL = 'usuarios.Usuario'


# Configuracao de sessao (item 1.9 e 1.10)
# Sessao expira apos 30 minutos de inatividade
SESSION_COOKIE_AGE = 1800  # 30 minutos em segundos
SESSION_SAVE_EVERY_REQUEST = True  # renova o tempo a cada acao do usuario
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # expira ao fechar o navegador

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Pasta onde o comando "collectstatic" reune todos os arquivos
# estaticos do projeto antes do deploy (exigido pelo whitenoise
# em producao)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        # Comprime e adiciona hash no nome dos arquivos estaticos
        # (ex.: style.a1b2c3.css), permitindo cache agressivo no
        # navegador sem risco de servir uma versao desatualizada
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Protecao contra forca bruta (item 1.11)
AXES_FAILURE_LIMIT = 5  # bloqueia apos 5 tentativas erradas
AXES_COOLOFF_TIME = 1  # bloqueio dura 1 hora
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # bloqueia por usuario e IP

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',

]

# Configuracao do 2FA (itens 1.5 e 1.6)
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = 'two_factor:profile'

# Configuracao de envio de email para recuperacao de senha (item 2.1)
# Em desenvolvimento, o "console backend" imprime o email no terminal
# em vez de enviar de verdade - facilita testar sem precisar de servidor de email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Tempo de expiracao do token de recuperacao de senha, em segundos (item 2.3)
# 3600 segundos = 1 hora (padrao do Django e 3 dias, reduzimos para maior seguranca)
PASSWORD_RESET_TIMEOUT = 3600

# Garante que a pasta 'logs/' exista antes do Django tentar escrever
# nela (necessario em producao, onde a pasta nao vem no repositorio)
(BASE_DIR / 'logs').mkdir(exist_ok=True)

# Configuracao de log para recuperacao de senha (itens 2.6 e 2.7)
# Registra em arquivo todas as solicitacoes e o resultado (sucesso/falha) do processo
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file_recuperacao_senha': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'recuperacao_senha.log',
        },
    },
    'loggers': {
        'usuarios.recuperacao_senha': {
            'handlers': ['file_recuperacao_senha'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# ============================================================
# Seguranca de comunicacao (Requisito 3.1 e 3.2)
# Essas configuracoes so entram em vigor quando DEBUG=False
# (ou seja, apenas em producao/hospedado, nunca no localhost)
# ============================================================

# Item 3.1: forca todo acesso HTTP a ser redirecionado para HTTPS
SECURE_SSL_REDIRECT = not DEBUG

# Necessario porque o Render fica atras de um proxy reverso; sem
# isso o Django nao consegue saber que a conexao original do
# usuario ja chegou via HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Item 3.2: garante que cookies de sessao e de CSRF so trafeguem
# por conexao criptografada, nunca em texto puro por HTTP
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# HSTS: instrui o navegador a nunca mais tentar acessar o site via
# HTTP no futuro, mesmo que o usuario digite http:// manualmente
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG