# Generated by Django 5.2.17 on 2026-09-13 01:21

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=usuarios.models.TelefoneCriptografadoField(blank=True, max_length=255, null=True, verbose_name='telefone'),
        ),
    ]
