# Generated by Django 5.2.17 on 2026-09-24 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo_teorico', models.TextField()),
                ('ordem', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['modulo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20)),
                ('ordem', models.PositiveIntegerField()),
                ('percentual_para_liberar', models.PositiveIntegerField(default=80)),
            ],
            options={
                'ordering': ['trilha', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla escolha'), ('verdadeiro_falso', 'Verdadeiro ou falso'), ('completar_codigo', 'Completar o código'), ('ordenar_linhas', 'Ordenar linhas de código')], max_length=20)),
                ('enunciado', models.TextField()),
                ('resposta_esperada', models.CharField(blank=True, max_length=255)),
                ('xp_recompensa', models.PositiveIntegerField(default=10)),
                ('ordem', models.PositiveIntegerField()),
                ('eh_teste_nivelamento', models.BooleanField(default=False)),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='gamificacao.licao')),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios', to='gamificacao.tema')),
            ],
        ),
        migrations.AddField(
            model_name='licao',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='gamificacao.modulo'),
        ),
        migrations.CreateModel(
            name='OpcaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('ordem_correta', models.PositiveIntegerField(blank=True, null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='gamificacao.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('streak_atual', models.PositiveIntegerField(default=0)),
                ('streak_recorde', models.PositiveIntegerField(default=0)),
                ('data_ultima_atividade', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='gamificacao.trilha'),
        ),
        migrations.CreateModel(
            name='ResultadoNivelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('modulo_confirmado_pelo_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamificacao.modulo')),
                ('modulo_sugerido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.trilha')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='gamificacao.trilha'),
        ),
        migrations.CreateModel(
            name='LiberacaoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('liberado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.modulo')),
            ],
            options={
                'unique_together': {('usuario', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoLicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.licao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'licao')},
            },
        ),
    ]
